run:
  deadline: 60m

linters:
  enable-all: true
  disable: nlreturn,ireturn,wsl,varnamelen,revive,depguard,err113,gomnd,execinquery,mnd,wrapcheck,gofumpt

linters-settings:
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 200
  nestif:
    # their are various nested if else, therefore specifying complexity as 26
    min-complexity: 26